version: '3.4'

networks:
  masterapinetwork:

services:
  masterapidb :
    container_name: masterapidb
    image : mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    networks:
        - masterapinetwork

  masterapi:
    container_name: masterapi-container
    build:
      context: .
      dockerfile: MASTERAPI/Dockerfile
    ports:
     - 8445:80
    depends_on:
     - masterapidb
    environment:
     - DB_HOST=masterapidb
     - DB_NAME=MDB
     - DB_SA_PASSWORD=password@12345#
    networks:
     - masterapinetwork


